# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mParticle-AppsFlyer-Example' do
  use_frameworks!

  pod 'mParticle-AppsFlyer', :path => '..'
end
