source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
xcodeproj 'Example'

def include_common_pods
    pod 'mParticle-Apple-SDK', :path => '../'
end

target :phoneApp do
    link_with 'iOS_Example'
    use_frameworks!
    platform :ios, '8.0'
    include_common_pods
end

target :tvApp do
    link_with 'tvOS_Example'
    use_frameworks!
    platform :tvos, '9.0'
    include_common_pods
end
