platform :ios, '15.0'

target 'mParticleExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for mParticleExample
  pod 'mParticle-Apple-SDK', :path => '..'
  pod 'mParticle-Apple-Media-SDK', '~> 1.3.1'
  pod 'mParticle-Rokt', '~> 8.0'
  #pod 'PLCrashReporter', '~> 1.11.1'
  #pod 'mParticle-UrbanAirship', :path => '../../mparticle-apple-integration-urbanairship'
  #pod 'mParticle-BranchMetrics', :path => '../../mparticle-apple-integration-branchmetrics'

  target 'mParticleExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mParticleExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  # target 'mParticleExample_Extension' do
      # pod 'mParticle-Apple-SDK/AppExtension', :path => '..'
  # end

end
