# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mParticle-Appboy-tvOS-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mParticle-Appboy-tvOS-Example
  pod 'mParticle-Appboy', :path => '../..'

  target 'mParticle-Appboy-tvOS-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mParticle-Appboy-tvOS-ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
