disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_cast
  - weak_delegate
  - function_parameter_count
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length

line_length:
  warning: 130
  error: 160
  ignores_comments: true
  ignores_urls: true

type_name:
  min_length: 1
  max_length: 40

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - UnitTests
