source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

abstract_target 'Example' do
    use_frameworks!
    pod 'mParticle-Apple-SDK', :path => '../../'

    target 'iOS_Example' do
        platform :ios, '8.0'
    end

    target 'tvOS_Example' do
        platform :tvos, '9.0'
    end

    target 'iOS7_Example' do
        platform :ios, '8.0'
    end
    
    target 'iOS_Extension_Example' do
        pod 'mParticle-Apple-SDK/AppExtension', :path => '../../'
        platform :ios, '9.0'
    end
end
