# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
source 'https://github.com/CocoaPods/Specs'
source 'git@github.com:mparticle/Specs'

target 'KitsExample' do
    pod 'mParticle-Apple-SDK', :path => '../..', :subspecs => ['Adjust', 'Appboy', 'AppsFlyer', 'comScore', 'Crittercism','Flurry', 'Kahuna', 'Kochava', 'Localytics', 'Tune', 'Wootric']
end
