# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
source 'https://github.com/CocoaPods/Specs'
source 'git@github.com:mparticle/Specs'

pre_install do |pre_i|
    def pre_i.verify_no_static_framework_transitive_dependencies; end
end

target 'KitsExample' do
    pod 'mParticle-Apple-SDK', :path => '../..'
    pod 'mParticle-Adjust'
    pod 'mParticle-Appboy'
    pod 'mParticle-AppsFlyer'
    pod 'mParticle-ComScore'
    pod 'mParticle-Crittercism'
    pod 'mParticle-Flurry'
    pod 'mParticle-Kahuna'
    pod 'mParticle-Kochava'
    pod 'mParticle-Localytics'
    pod 'mParticle-Tune'
    pod 'mParticle-Wootric'
end
