# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

target 'Cocopods-Objc-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Cocopods-Objc-Example
  pod 'mParticle-Braze-12', :path => '../..'

end
