name: Secondary Platforms iOS Build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  XCODE_VERSION: "16.4"

jobs:
  build-react-native:
    runs-on: macOS-15
    defaults:
      run:
        working-directory: ./RNExample/ios
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup specified simulator
        uses: futureware-tech/simulator-action@e89aa8f93d3aec35083ff49d2854d07f7186f7f5 # v5
        id: simulator
        with:
          model: iPhone 16 Pro
          os: iOS
          os_version: ">=18.0"
          erase_before_boot: true
          wait_for_boot: true
          shutdown_after_job: true

      - name: Install React Native dependencies
        working-directory: ./RNExample
        run: npm ci

      - name: Update CocoaPods repo
        run: pod repo update

      - name: Install CocoaPods dependencies
        run: pod install

      - name: Build iOS extension scheme
        env:
          SAFE_STEPS_SIMULATOR_OUTPUTS_UDID: ${{ steps.simulator.outputs.udid }}
        run: xcodebuild -allowProvisioningUpdates -workspace RNExample.xcworkspace -scheme RNExample -destination "id=${SAFE_STEPS_SIMULATOR_OUTPUTS_UDID}"
