name: Xcode Tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  XCODE_VERSION: "16.4"

jobs:
  native-unit-tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [iOS, tvOS]
        scheme: [mParticle-Apple-SDK, mParticle-Apple-SDK-Swift]
        include:
          - platform: iOS
            device: iPhone 16 Pro
          - platform: tvOS
            device: Apple TV 4K (3rd generation)
    runs-on: macOS-15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup specified simulator
        uses: futureware-tech/simulator-action@e89aa8f93d3aec35083ff49d2854d07f7186f7f5 # v5
        id: simulator
        with:
          model: ${{ matrix.device }}
          os: ${{ matrix.platform }}
          os_version: ">=18.0"
          erase_before_boot: true
          wait_for_boot: true
          shutdown_after_job: false

      - name: Wait for simulator to finish booting
        env:
          SAFE_STEPS_SIMULATOR_OUTPUTS_UDID: ${{ steps.simulator.outputs.udid }}
        run: xcrun simctl bootstatus "${SAFE_STEPS_SIMULATOR_OUTPUTS_UDID}" -b

      - name: Run unit tests
        env:
          SAFE_STEPS_SIMULATOR_OUTPUTS_UDID: ${{ steps.simulator.outputs.udid }}
        run: |
          xcodebuild -project mParticle-Apple-SDK.xcodeproj \
            -scheme ${{ matrix.scheme }} \
            -destination "id=${SAFE_STEPS_SIMULATOR_OUTPUTS_UDID}" \
            -parallel-testing-enabled NO \
            -test-timeouts-enabled YES \
            -default-test-execution-time-allowance 120 \
            test
